### ISSUE TITLE
Hard to find external trigger destination jobs

### ISSUE THREAD

**Issue by yuichi10** [screwdriver-cd/screwdriver#1333]
**What happened**:
Now hard to find external trigger destination jobs. Also I can't find out the job is used by external trigger or not.

**What you expected to happen**:
I want to know the job is external trigger or not and want to know where the trigger is going.
Also triggers should be clickable so that user can navigate across pipelines

**How to reproduce it**:
using external trigger.

**Comment by tkyi** [comment]
Adding an endpoint to get the related triggers first:
`GET /pipelines/:pipelineId/triggers`
 Should return something like:
```
{
  main: ['~sd@12345:main'],
  beta: ['~sd@12345:test', '~sd@223344:test'],
  prod: ['~sd@556677:deploy']
}
```

**Comment by tkyi** [comment]
Adding some extra data:

---
For this story, we see two major use cases for using external triggers:
1. A single user "A" wants to link two of their own pipelines.
2. User "A" creates a pipeline that publishes an npm package. Users "B", "C", "D" want to rebuild their pipelines when changes to the npm package are made.

In case 1, it makes sense to show another node on the pipeline graph so user "A" can easily navigate to their downstream external job/pipeline.
In case 2, it makes a lot less sense for user "A" to see other people's downstream external job/pipeline on their pipeline graph.

---
*Update*: We're having our designer take a stab at the UI, but it's still unclear to me what makes the most sense.

*Another possible issue*: we don't store historical data for external triggers. If a user sets up an external trigger, it will show up on all event graphs. That might be confusing for the user.

**Comment by tkyi** [comment]
## TODO

- [x] `models`: add function to get triggers given a pipeline ID
- [x] `API`: add endpoint to `GET pipelines/:pipelineid/triggers`
- [ ] `UI`: add toggle to show external triggers; add external node on pipeline event graph with links to external triggers

**Comment by tkyi** [comment]
Should be able to toggle to show triggers in UI.
<img width="886" alt="Screen Shot 2019-05-23 at 6 03 12 PM" src="https://user-images.githubusercontent.com/3230529/58838361-54fedc00-8613-11e9-941f-7828e585ba01.png">
<img width="883" alt="Screen Shot 2019-05-23 at 6 02 57 PM" src="https://user-images.githubusercontent.com/3230529/58838362-54fedc00-8613-11e9-99ba-d5d20f3b51e1.png">

**Comment by tk3fftk** [comment]
We found a bug related this feature.
Another screwdriver.yaml is load (from repo root) when `Hide triggers` is selected in [this pipeline](https://cd.screwdriver.cd/pipelines/2897/events).
![external_trigger_ui_bug](https://user-images.githubusercontent.com/3445553/58848296-f55f0a00-86c0-11e9-8b8c-f6b64fa30a33.gif)

**Comment by tk3fftk** [comment]
@jithin1987 Do we have another issue about https://github.com/screwdriver-cd/screwdriver/issues/1333#issuecomment-498503641 ?
