### ISSUE TITLE
screwdriver yaml for mono repo can grow big and hard to maintain

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#1455]
**What happened**:

`sourcePaths` feature which  is used to construct monorepo based workflow can result in a large `screwdriver.yaml` file depending on the number of sub projects in the repository. In order to better manage workflow of individual sub projects in a monorepo, separating out `screwdriver.yaml` configurations for the sub projects will result in smaller and maintainable workflow configuration files

**What you expected to happen**:

**How to reproduce it**:

**Comment by tkyi** [comment]
Would this feature basically be a way to specify where source code is?
Currently, `screwdriver.yaml` and all other files are relative to root. We could allow users to specify `root` in their screwdriver.yaml file. All files and things would be taken relative to that root.

```
jobs:
    main:
        image: node:6
        requires: [~pr, ~commit]
        root: "src/app/"
        steps:
            - echo: echo hi
```

**Comment by jithin1987** [comment]
I am thinking of supporting multiple `screwdriver.yaml` configurations at sub directories which leads to separate different pipelines. There are two use cases here.

1. With source paths.
    With source paths, multiple `screwdriver.yaml` files will still have a single pipeline, but config for different `sourcePaths` will come from separate `screwdriver.yaml` files. This approach will have  only one pipeline.
1. Without source paths.
    This will be the simplest to implement. Uniqueness of the pipeline now won't be just repo + branch. But repo + branch + path to `screwdriver.yaml` file. This approach will lead to multiple pipelines.

**Comment by minz1027** [comment]
I think combined it with sourcePaths is making this very complicated. Cuz when user has a yaml under a subdir, they probably expect cmd ran relative to that subdir. If that subdir doesn't match the sourcePath, we do we do? When we create the workspace, where should we point to? Also to parse the yaml, if you want to have a sub yaml with multiple jobs, how would that look like? Since from the root yaml, you need to defined A job with with sourcePaths first.

e.g.
```jobs:
    main:
        image: node:6
        requires: [~pr, ~commit]
        sourcePaths: ["src/app/", "test/abc"]
        configPath: someDir
```

**Comment by minz1027** [comment]
I think the second way is neat and simpler. But that root / sourceDir config cannot come from the yaml. We need to have that when user create the pipeline since that will be part of the unique constraints.

**Comment by jithin1987** [comment]
> I think combined it with sourcePaths is making this very complicated. Cuz when user has a yaml under a subdir, they probably expect cmd ran relative to that subdir. If that subdir doesn't match the sourcePath, we do we do? When we create the workspace, where should we point to? Also to parse the yaml, if you want to have a sub yaml with multiple jobs, how would that look like? Since from the root yaml, you need to define A job with with sourcePaths first.

With first approach there is no change to how `sourcePaths` works today. It's just a way to abstract out parts of `screwdriver.yaml` file to make it nimbler. Think of it more like `import` statements for a parts of pipeline. So CWD won't change from how it's run today.

> I think the second way is neat and simpler to implement. But that root / sourceDir config cannot come from the yaml. We need to have that when user create the pipeline since that will be part of the unique constraints.

Agreed. User needs to provide full path to yaml when creating pipeline if not at root.

**Comment by minz1027** [comment]
## TODO
- [ ] data-schema: make rootDir part of scmUri
- [ ] scm-base, scm-router, scm-github: parseUrl takes in optional rootDir and return scmUri with rootDir; getFile; decorateUrl
- [ ] launcher: set the working space and work dir properly if there is a rootDir

**Comment by DekusDenial** [comment]
hmm, it looks a lot like the hierarchical configuration inheritance depicted in many tools these days, e.g. babel and typescript. Maybe introduce a new keyword like `extend` will help here. Also, are we talking about creating ONE pipeline or MULTIPLE pipelines here? I assume this is just for monorepo...

**Comment by tkyi** [comment]
*Update 5/15:*
---
Some issues cloning to SD_SOURCE_DIR after we changed it in the launcher. Need to go back and revert that change. https://cd.screwdriver.cd/pipelines/2818/builds/114662/steps/sd-setup-scm

**Comment by jithin1987** [comment]
Also create pipeline API call should fail, if SCM is not a supported one.

**Comment by tkyi** [comment]
This feature should be complete.
Docs: https://docs.screwdriver.cd/user-guide/configuration/sourceDirectory.html
Blog post: https://blog.screwdriver.cd/post/185111486992/custom-source-directory
