### ISSUE TITLE
Repository webhooks

### ISSUE THREAD

**Issue by FenrirUnbound** [screwdriver-cd/screwdriver#379]
## Scenario

When creating a Screwdriver pipeline for my repository, a webhook is not added to the target repository. This means that when the target branch is updated either by directly pushing to it or merging in a Pull-Request, a new build has to be manually initiated. 

Adding a webhook to the repository solves this, but is also a manual task.

Automating this manual work would ease the on-boarding process.

## Tasks

- [x] Update `scm-base` to expose an endpoint for adding a webhook
   - [x] Implement the functionality in `scm-github`
      - [ ] Clean up/Refactor to not test against pseudo-private functions
   - [x] Implement the functionality in `scm-bitbucket`
      - [x] determine permissions scope
      - [ ] Clean up/Refactor to not test against pseudo-private functions
- [x] Integrate the functionality in the `Pipeline`/`PipelineFactory` model.
   - [x] Decide on whether it happens during `create` or `sync`
   - [x] Clean up/Refactor the `.sync` operation

## Related Issues

- screwdriver-cd/screwdriver#219

### 2016-12-6
* Additional item for `scm-bitbucket`. There was some work with exploring which permissions were needed to modify webhooks for a repository.

### 2016-12-12
* As part of PR feedback, we included tasks for refactoring and cleaning up.

**Comment by FenrirUnbound** [comment]
PoC

```javascript
'use strict';

const Github = require('github');
const client = new Github({
  debug: false,
  protocol: 'https',
  host: 'api.github.com',
  headers: {
    'user-agent': 'FenrirUnbound-client'
  }
});

client.authenticate({
  type: 'oauth',
  token: process.env.AUTH_TOKEN || ''
});

const events = ['pull_request', 'push'];
const config = {
  url: 'https://api.screwdriver.cd/v4/webhooks',
  content_type: 'json',
  secret: 'someSecretGoesHere'
};
client.repos.createHook({
  owner: 'FenrirUnbound',
  repo: 'wallball',
  name: 'web',  // defined by list - https://api.github.com/hooks
  config,
  events,
  active: true
}).then(console.log);

```

**Comment by FenrirUnbound** [comment]
Instead of guessing what the API is supposed to be in `scm-base`, we're implementing it in both `scm-github` and `scm-bitbucket` first. Once we have a baseline for what inputs each of these implementations require, we'll refactor it up into the `scm-base`.

**Comment by FenrirUnbound** [comment]
PoC for bitbucket.org usage.

Things we would need to verify:

- [ ] which events to enable
- [ ] updating an event

```
const API_URL = 'https://api.bitbucket.org/2.0';
const requestLib = require('./request');
const token = process.env.AUTH_TOKEN || '';
const username = process.env.USERNAME || '';
const url = `${API_URL}/repositories/fenrirunbound/yabba-client/hooks`

function list() {
    const config = {
        url: `${url}?pagelen=1&page=3`,
        method: 'GET',
        auth: {
            username,
            password: token
        },
        json: true
    };

    return request(config)
    .then(([err, req, body]) => {
        console.log(req.statusCode);
        console.log(body);
    });
}

function createHook() {
    let config = {
        url,
        method: 'POST',
        auth: {
            username,
            password: token
        },
        body: {
            description: 'My description2',
            url: 'https://screwdriver.cd/somewhere',
            active: true,
            events: [
                'repo:push',
                'pullrequest:updated',
                'pullrequest:created'
            ]
        },
        json: true
    };

    return request(config)
    .then(([err, response, body]) => {
        console.log(response.statusCode);
        console.log(JSON.stringify(response.body));
    });
}
```

Output

```
$ USERNAME=`cat user` AUTH_TOKEN=`cat secret` node poc
200
{ next: 'https://api.bitbucket.org/2.0/repositories/fenrirunbound/yabba-client/hooks?pagelen=1&page=3',
  values: 
   [ { read_only: null,
       description: 'My description1',
       links: [Object],
       url: 'https://screwdriver.cd/somewhere',
       created_at: '2016-12-06T00:18:03.802023Z',
       skip_cert_verification: false,
       source: null,
       active: true,
       subject: [Object],
       type: 'webhook_subscription',
       events: [Object],
       uuid: '{7b71be13-0c19-44e1-bd75-b6362445bf18}' } ],
  pagelen: 1,
  size: 3,
  page: 2,
  previous: 'https://api.bitbucket.org/2.0/repositories/fenrirunbound/yabba-client/hooks?pagelen=1&page=1' }

$ USERNAME=`cat user` AUTH_TOKEN=`cat secret` node poc
200
{ pagelen: 1,
  previous: 'https://api.bitbucket.org/2.0/repositories/fenrirunbound/yabba-client/hooks?pagelen=1&page=2',
  values: 
   [ { read_only: null,
       description: 'My description',
       links: [Object],
       url: 'https://screwdriver.cd/somewhere',
       created_at: '2016-12-06T00:16:38.690248Z',
       skip_cert_verification: false,
       source: null,
       active: true,
       subject: [Object],
       type: 'webhook_subscription',
       events: [Object],
       uuid: '{84c4e87c-50a5-4bfd-b142-c2538ebd5c9a}' } ],
  page: 3,
  size: 3 }
```

**Comment by tkyi** [comment]
**Status:** Waiting on #399 before merging

_NOTE: Looks like webhooks were added to individual repos and we have been manually deleting duplicates from individual repos (and keeping the org-wide webhook) for now to prevent duplicate builds from being triggered_

**Comment by tkyi** [comment]
Merged #403 
Waiting for it to run through the pipeline successfully

**Comment by stjohnjohnson** [comment]
Works great for me!
