### ISSUE TITLE
Build page Epic

### ISSUE THREAD

**Issue by minz1027** [screwdriver-cd/screwdriver#396]
- [ ] redesign build page header
- [ ] floating "go to top" button
- [ ] permalinks to steps - [WIP] petey
- [x] links to next/previous job in pipeline

**Comment by stjohnjohnson** [comment]
Replacing with https://github.com/screwdriver-cd/screwdriver/issues/423
