### ISSUE TITLE
UX Improvement Epic

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/screwdriver#423]
This issue is to track overall improvements we want in the Screwdriver experience.  It's a mini-backlog of items that we want to change.

When making changes related to items in here:
 - If it's small, the PR should be tagged to this issue.
 - If it's large, a new issue should be created to track the progress (and tagged here).

----
## Stories/Tasks

**Build Page:**
- [x] redesign build page header
- [x] floating "go to top" button
- [ ] [permalinks to steps](https://github.com/screwdriver-cd/screwdriver/issues/962)
- [ ] [links to next/previous job in pipeline](https://github.com/screwdriver-cd/screwdriver/issues/958)
- [ ] [display metadata](https://github.com/screwdriver-cd/screwdriver/issues/674)

**Validator/Configurator Page:**
 - [x] Validator page

**[Favorite Pipelines/Collections](https://github.com/screwdriver-cd/screwdriver/issues/523):**
 - [x] sharable links
 - [x] overall view of combined pipelines

**Pipeline View:**
 - [x] complete subway map (https://github.com/screwdriver-cd/screwdriver/issues/803)
 - [x] job description
    - [x] shows up in validator (https://github.com/screwdriver-cd/data-schema/pull/149, https://github.com/screwdriver-cd/data-schema/pull/151, https://github.com/screwdriver-cd/config-parser/pull/38)
     - [x] shows up in UI (https://github.com/screwdriver-cd/ui/pull/174)
 - [ ] [disabled job reason](https://github.com/screwdriver-cd/screwdriver/issues/815)
 - [x] add ability to rebuild at a given job/event (https://github.com/screwdriver-cd/screwdriver/issues/806)
 - [ ] [pipeline health metric](https://github.com/screwdriver-cd/screwdriver/issues/1412)
 - [ ] [improved tooltips on build bubbles](https://github.com/screwdriver-cd/screwdriver/issues/1045)
 - [ ] [make event retries more obvious](https://github.com/screwdriver-cd/screwdriver/issues/671)
 - [x] do something about the Start button
    - [x] move Start button to left side so it's easier to find
 - [x] make it more obvious when logged in or not (Start button disappears)

## Changelog

2017-6-28
- Added links to job descriptions PRs and additional bullet points under
- Added more bullets after "do something about the Start button"

2017-8-16
- Added link to Favorites issue

2017-9-28
- Added link to event retries reason issue

2017-12-4
- Added link to subway map and ability to rebuild at a given job/event

2018-5-2
- Added link to next builds navigation links

2018-6-5
- Added more relevant issue links

2019-4-4
- Added another link to another issue

**Comment by tkyi** [comment]
Since the rest of the asks in this issue are tracked by their own issues, closing out this one in favor of the more detailed issue.
