### ISSUE TITLE
Securely build Docker images

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#595]
We need to provide users a way to build docker images inside of a build. This requires securely exposing a docker socket to the build container and allowing docker to run in privileged mode. The solution to this will require builds to run in a VM, and the docker socket to be mounted into the container running the build.

To accomplish this we need to do the following:
- [x] Annotations for Feature Configuration #580
- [x] Create alternative pod template to support builds in VMs #597 
- [x] Support for multiple executors #604 
- [x] Consume annotations to choose executor resource (detailed below) https://github.com/screwdriver-cd/models/pull/177
- [x] New executor to support VM in k8s (https://github.com/screwdriver-cd/executor-k8s-vm)

**Comment by FenrirUnbound** [comment]
> Consume annotations to choose executor resource

The task is so small it's not worth making an elaborate issue for it 😺 

Someone correct me if I'm wrong. I believe the annotation we decided on was `alpha.screwdriver.cd/executor`. Although we don't plan on enforcing validation on what inputs are legitimate, the only ones we will utilize are `k8s` and `k8s-vm`

**Comment by minz1027** [comment]
Currently, we have the annotations key as `beta.screwdriver.cd/executor` in our code.
> Consume annotations to choose executor resource
Tasks resolved by the above PR ^^

**Comment by tkyi** [comment]
@FenrirUnbound Actually we agreed on `beta.screwdriver.cd/executor` 😛 
https://github.com/screwdriver-cd/executor-router/blob/master/index.js#L3
