### ISSUE TITLE
Templates - Second Pass

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#616]
*Background* See https://github.com/screwdriver-cd/screwdriver/issues/470

- [x] Wrapping around the steps inside template. For example: pretest, posttest. (https://github.com/screwdriver-cd/config-parser/pull/39)
Inside template:
```yaml
   steps: 
       - test: echo test
       - publish: echo publish
```

Inside user's screwdriver.yaml:
```yaml
main:
   template: mytemplate@1
   steps: 
       - pretest: echo hello
       - posttest: echo goodbye
```

Translates into: 
```yaml
   steps:
       - pretest: echo hello
       - test: echo test
       - posttest: echo goodbye
       - publish: echo publish
```

- [x] Override step: (https://github.com/screwdriver-cd/config-parser/pull/40)
```yaml
main:
   template: mytemplate@1
   steps: 
       - publish: echo not publishing
```

Translate into:
```yaml
   steps:
       - test: echo test
       - publish: echo not publishing
```

- [x] [Version tags](https://github.com/screwdriver-cd/screwdriver/issues/616#issuecomment-314568245) (__WIP__): crud api for tagging template versions, e.g. npm's `dist_tags` allow fetch on template version by tag. `mytemplate@latest` (https://github.com/screwdriver-cd/data-schema/pull/157, https://github.com/screwdriver-cd/data-schema/pull/158, https://github.com/screwdriver-cd/models/pull/179, https://github.com/screwdriver-cd/config-parser/pull/41, https://github.com/screwdriver-cd/screwdriver/pull/646, https://github.com/screwdriver-cd/screwdriver/pull/647)
- [ ] Restrict API calls for template writes to admins, and template owners
- [ ] Version Lifespan: After a set period of time [configurable: default 6 months], a given version of a template should display a warning message in the build that the template is no longer being updated/maintained. (https://github.com/screwdriver-cd/screwdriver/issues/1490)
- [x] [Template namespaces](https://github.com/screwdriver-cd/screwdriver/issues/926) (e.g.: chef/publish, screwdriver/checkout, etc) 
- [ ] Template keywords: Listed in annotations of template.yaml, e.g. `language:node.js`, `publishing`, `aws`. Primarily to allow discovery of templates by searching by keyword. Keywords should apply to all versions of a template.
- Documentation in guide:
   - [x] create, validate, and publish (https://github.com/screwdriver-cd/guide/pull/90)
   - [x] wrapping around steps (https://github.com/screwdriver-cd/guide/pull/95)
   - [x] overriding steps (https://github.com/screwdriver-cd/guide/pull/96)
   - [x] tagging (https://github.com/screwdriver-cd/template-main/pull/8, https://github.com/screwdriver-cd/template-main/pull/9, https://github.com/screwdriver-cd/template-main/pull/10, https://github.com/screwdriver-cd/guide/pull/105)
   - [ ] lifespan
   - [x] namespaces
   - [ ] keywords
- [ ] Blog post

Nice to have:
- [x] Publish multiple templates from one repo

### 2017-7-6
- Added PR link for wrapping steps

### 2017-7-10
- Added PR link for create, validate, and publish documentation
- Added documentation requirements for wrapping and overriding steps

### 2017-7-13
- Added PR links for data schema and models for tagging

### 2017-7-14
- Added PR link for tagging API, tags in config-parser

### 2017-7-24
- Added checkbox for template namespacing

### 2017-7-28
- Added links to template tagging module and documentation PRs

### 2018-3-19
- Added link to template namespace issue

**Comment by d2lam** [comment]
## Template tagging
For template tagging, we decided to have a new table called `templateTags`. 
This will be a map of `tag` and `version`. 
1 version can be mapped to multiple tags, but 1 tag can only be mapped to 1 version. 

**Example:** `mytemplate@1.2.0` can be tagged as `stable` and `latest`

The templateTags table will look like this

| id | name | tag | version | 
|---|---|---|---|
| 1 | mytemplate | stable | 1.2.0 | 
| 2 | mytemplate | latest | 1.2.0 | 

If they retag `stable` with version `1.1.0`, then the table will look like 

| id | name | tag | version | 
|---|---|---|---|
| 1 | mytemplate | stable | 1.1.0 | 
| 2 | mytemplate | latest | 1.2.0 |

**Comment by FenrirUnbound** [comment]
Some notes with using it as of writing:

1. Tagging in a build isn't easy

The publishing operation does not make it easy to determine what version was published. The only indicator about the new version is this message: 

> Template FenrirUnbound/my-template@1.2.18 was successfully published

In order to determine the exact version that was published, we need to:

* save the output of the publish to a file
* parse the file for the exact version that was published
* save that version to be used with the tagging operation

This problem kind of goes away if the template owner explicitly defines a `major.minor.patch` version in their `sd-template.yaml`. The oddities with this method is that you have to be sure to change it in two places, and you can't run more than one build without a code change.

2. Defining the `--name` value should be implied

Having an option for `--name` to be provided is nice to explicitly define the template to tag. It would be more convenient to have that value determined by the `sd-template.yaml` file. The publish operation determines the name based on the `sd-template.yaml` file so I would expect that the tagging operation would infer the same value.
