### ISSUE TITLE
Build Periodically

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#688]
# Context
As a user,
I would like to schedule a pipeline to execute periodically,
So I can ensure that my code and dependencies are always up-to-date.

## Objective
Allow the user to supply an annotation describing a cron-style string which describes the interval for which a job should run. This interval should *not* be allowed to occur more than once hourly. We can enforce this by requiring the "minutes" configuration to be `H`.

### H Explanation
Note: To allow periodically scheduled tasks to produce even load on the system, the symbol "H" (for "hash") should be used wherever possible. For example, using 0 0 * * * for a dozen daily jobs will cause a large spike at midnight UTC. In contrast, using H H * * * would still execute each job once a day, but not all at the same time, better using shared resources. The "H" symbol can be used with a range. For example, H H(0-7) * * * means some time between 12:00 AM UTC (midnight) to 7:59 AM UTC. You can also use step intervals with "H", with or without ranges.

### Tasks
- [x] Spike
- [x] Define a workflow annotation for storing periodic build configuration
- [x] A workflow automatically creates an event when the periodic build configuration triggers
- [x] Enable `H` configurations
- [x] Document annotation
- [ ] Monitor frequently running pipelines so that we can detect abuse

**Comment by minz1027** [comment]
### Possible solution
- Kubernetes cron job
- micro service
- at queue level

**Comment by pranavrc** [comment]
@Filbird and I were looking into this, and https://github.com/resque/resque-scheduler#dynamic-schedules seems like the cleanest way to implement this since it would happen at the executor-queue level when we create the job in the queue. It supports recurring jobs with dynamic schedules.

**Comment by Filbird** [comment]
**Update 4/18**

Implementing this at a the `executor-queue` [level](https://github.com/screwdriver-cd/executor-queue/blob/master/index.js#L64) requires us to persist the JWT beyond its intended lifespan. One idea is to generate a new JWT by using the OAuth token to hit the `/v4/auth/login/` endpoint as detailed [here](https://docs.screwdriver.cd/user-guide/api#authentication-and-authorization). The JWT would then be stored in Redis prior to enqueueing the scheduled build in Resque.

Several complications:
- How do we get a unique build ID for every scheduled build?
- How do we ensure only a single instance of the scheduler is enqueueing builds?

**Comment by Filbird** [comment]
**Update 4/19**

In order to ensure that the API remains stateless, we are proposing the implementation of this feature as a microservice named [`sd-scheduler`](https://github.com/screwdriver-cd/sd-scheduler). The microservice will expose an endpoint for POSTing a new periodic build. The associated handler will in turn bear the responsibility of scheduling builds by POSTing to the `/v4/events` [endpoint](https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/events/create.js).

To do this we introduce a new method in the [`executor-base`](https://github.com/screwdriver-cd/executor-base/blob/master/index.js#L25) interface named `recurringStartBuild` This method is called upon job creation in the [jobFactory](https://github.com/screwdriver-cd/models/blob/master/lib/jobFactory.js#L44), passing in the pipeline ID, job ID, periodic annotation, and admin token. The admin token will be used for generating a new JWT prior to scheduling a new build.

For our purposes, we will only implement this method in the [`executor-queue`](https://github.com/screwdriver-cd/executor-queue/blob/master/index.js#L10).  The method will make a POST to the microservice with the aforementioned arguments as the payload. 

More details to follow.

**Comment by Filbird** [comment]
**Update 4/25**

Started work on implementing `startPeriodic` (previously `recurringStartBuild` and `stopPeriodic` functions within [`executor-base`](https://github.com/screwdriver-cd/executor-base/pull/39/files) and [`exexutor-queue`](https://github.com/screwdriver-cd/executor-queue/pull/12/files). We pass the `tokenGen` function from the [API](https://github.com/screwdriver-cd/screwdriver/pull/1032)

Also began work on parsing/validation of the build periodically annotation. This should take place in the executor level rather than within [`config-parser`](https://github.com/screwdriver-cd/config-parser). In order to emulate the Jenkins `H` configuration cron expression, we default the minutes tab to `H` and determine a value between [0-59] through hashing the jobId and performing a modulus operation. Similarly, all other `H` values are transformed appropriately to a proper cron expression that is accepted by `node-schedule`.

**Comment by Filbird** [comment]
**Update 4/26**

Cron expression parsing, transformation, and validation is almost complete. Similar to the Jenkins plugin, we handle the following inputs:
- `H * * * *`
- `H H/5 * * *`
- `H H(0-5) * * *`
- `H H(0-5)/5 * * *`
- `H 1,2,3,H(0-5) * * *`

Since we handle this at the executor level, we do not have a way to display to the end user that their configuration is invalid. Rather, we silently do not execute the user's periodic build.

**Comment by d2lam** [comment]
**Update 4/27**
PRs that are ready:
- https://github.com/screwdriver-cd/screwdriver/pull/1032
- https://github.com/screwdriver-cd/models/pull/239
- https://github.com/screwdriver-cd/executor-base/pull/39

**TODO:**
- config-parser 
- executor-queue

**A few clarification so we remember later on:**
- `node-resque's scheduler` does not do the periodic scheduling.
- To do the cron style scheduling, we need to use a package called `node-schedule`. It's indicated in the documentation here: https://github.com/taskrabbit/node-resque#job-schedules
- However, we might not be able to use it since it keeps track of the scheduled jobs (the job returned from `schedule.scheduleJob()`, not the screwdriver job) in memory. If our API pod crashes, we cannot retrieve the past scheduled jobs. We thought of using Redis to keep track, but it cannot store the entire job object. If we do serializing and deserializing it, they will be different objects and therefore, defeats our purpose.
- We might need to implement the logic ourselves.

**Comment by Filbird** [comment]
Continuing from the update above:

Here is a preliminary PR for the parsing the cron: 
https://github.com/screwdriver-cd/executor-queue/pull/13

**Comment by d2lam** [comment]
Moving this to done since the UX is tracked in a separate issue
