### ISSUE TITLE
Support new Workflow config

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#723]
# Context
As a pipeline owner,
I want to describe my pipeline from the job perspective,
So I do not need to write more than I have to to define a workflow.

## Objective
Using the new workflow spec, implement the serial flow of jobs, A->B->C, as it currently exists with the current workflow system. If both new and old workflow definitions exist in the same yaml, then the new workflow style takes precedence. Users of the old workflow spec should be shown a deprecation warning.

## Tasks
- [x] Publish the new workflow spec  (https://github.com/screwdriver-cd/screwdriver/blob/master/design/workflow.md)
- [x] Display a deprecation warning in build (and UI?) when a yaml defines `workflow`
- [x] Jobs defined with `requires: ~pr` are started by `pull-request` events
- [x] Jobs defined with `requires: ~commit` are started by `push` events
- [x] Jobs defined with `requires: [A]` are started after job `A` finishes successfully
- [x] Jobs without `requires` are ignored.

**Comment by d2lam** [comment]
## 9/29
We decided to not use the field `workflow` to decide whether it's a new or old workflow version. 

The reasons is:
Currently, we allow implicit workflow. That is, users can have 1 job (`main`) and not defined the `workflow` keyword. It will will be interpreted as `workflow: ['main']`. Or users can have a list of job, and the workflow will be interpreted as the same order that the jobs are defined. 

If we use the keyword `workflow` to decide whether it is a new/old version, then it will be ambiguous whether we want it to be a detached job (as described in the design doc), or we want it to be `requires:~commit`, `requires:A` 

### Our decision: 
**Check if any jobs has the `requires` keyword. If it doesn't, then we treat it like the old version.**

**Comment by d2lam** [comment]
## 10/05
We decided to have a new endpoint to create Event. The event will have a new field called `startFrom`. 
This field is a string that is a jobName `A` or a requires value like `~commit`
The UI can make call this endpoint when the user clicks start (`startFrom` will be `~commit` in this case)
With this change, we will get partial events.

**Comment by stjohnjohnson** [comment]
@petey what is left to do here?

**Comment by petey** [comment]
We need to officially deprecate and remove all the code for the old workflow system.

**Comment by d2lam** [comment]
**4/9/18** 
I will work on deprecating the old workflow.

**Comment by marian-r** [comment]
Is #874 going to be part of this? I'm asking as it is being referenced there.

**Comment by d2lam** [comment]
**Update 4/10/18**
4 PRs opened to deprecate workflow:
- workflow-parser
- config-parser
- models
- api

**TODO:**
- Fix feature tests in API
- changes to data-schema

**Comment by d2lam** [comment]
**4/18/2018**
This change is rolled out. 
Closing this issue.
