### ISSUE TITLE
[Tech Debt] Replace Executor Router with Executor Queue

### ISSUE THREAD

**Issue by petey** [screwdriver-cd/screwdriver#725]
# Context
We want everything to go through the queue infrastructure, so we should replace the Router with the Queue Executor. Since we currently have another Executor Router in the workers, those should be able to use the correct executor based on job annotations.

## Objective
Queue everything, process executor(s) in the queue workers

### Tasks
- [x] [Spike] Can we still ship sd-in-a-box without requiring all the queue infrastructure.
- [x] Remove logic in api for executor router
- [x] Queue workers use job annotations & executor router to start correct executor

### Optional
~~- [ ] Executor Queue will route to specific workers based on executor annotation~~
~~- [ ] Queue workers implement one executor strategy instead of executor router~~

#### Changelog:
10/6: Cross out optional tasks.
