### ISSUE TITLE
Persist meta from trigger jobs

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#771]
# Context
 
With `build after` feature https://github.com/screwdriver-cd/screwdriver/issues/768 a user can configure a job to be run in response to another job in different or same pipeline. As a pipeline owner I need to access meta set from trigger job from the external pipeline. (Job already have access if it's in same pipeline)

# Objective 

Allow job to access meta set from an external job/pipeline if it's provided in `requires` . Eg:  Trigger job can define variables like Artifact name/version which will be useful in triggered job (job which defines rebuild_on)

## Syntax

`meta get --external sd@PIPELINE_ID`

## Phase 1

- [ ] Meta from pipeline which triggered current should be available when user requests it with above syntax.

**Comment by d2lam** [comment]
This is now done. 

This pipeline is triggered by another pipeline that does `meta set foo barrrrrr`, and the metadata is available in this external triggered job. 
![screen shot 2017-11-28 at 11 03 56 am](https://user-images.githubusercontent.com/3401924/33338744-dc5e8a9c-d42b-11e7-8d2c-731e73860426.png)

**Comment by tkyi** [comment]
**Update 11/28:**
After some discussion, it seems safer to save the trigger job metadata in a separate blob from the current pipeline's metadata. We're working on changes to make this happen. 

Meta-cli can be used like so:
```
meta get foo --external sd@123:component
```

This work can be broken down into these tasks:
- [ ] Meta-cli can take in an `external` argument and will get/set metadata to that file
- [ ] Launcher will take the `parentBuildId` and make calls to the API to get the metadata from the trigger job

**Comment by d2lam** [comment]
**Update 11/29**
- PRs opened for both Launcher and Meta-cli

**Implementation details:**
- Launcher makes API calls to check if the current build and the triggering build belong to the same pipeline. 
     -  If they belong to the same pipeline, then we store `metadata` into the same `meta.json`. 
     -  If they belong to different pipelines (meaning this is an external trigger), we store `metadata` into the triggering job `sd@123:component.json`
- Meta-cli reads from `meta.json` or `sd@123:component.json` depending on the command. 
     - If asking for `meta get foo`, it will read from `meta.json`
     - If asking for `meta get foo --external sd@123:component`, it will read from `sd@123:component.json`
     - If it's asking from a some other pipeline `meta get foo --external sd@345:main`. This file doesn't exist so this step will fail. In the future, this should return the metadata of the last successful build.

**Comment by d2lam** [comment]
**Update 12/1**
This is now working with an additional flag: 
![screen shot 2017-12-01 at 11 02 39 am](https://user-images.githubusercontent.com/3401924/33498764-756a2a36-d687-11e7-986b-5f56160e3937.png)

According to @stjohnjohnson, we should fail the step if the build is trying to `set`. I'll modify `meta-cli` to fix this.

**Comment by d2lam** [comment]
This is done!
