### ISSUE TITLE
Start build for any job in pipeline

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#806]
## Context
As a user I want to start my pipeline at a specific job.

## Objective

As of today auto trigger for a pipeline's event is either `commit` or `pr` or an external pipeline's job. Also user can manually start a pipeline which behaves similar to `commit` triggered from last commit on configured SCM repo's branch.

Expose in UI a way for user to start pipeline from a specific job.

**Tasks**

- [x] UI pipeline graph for an event should expose a `Start Build` button against a job in the pipeline.

- [x] On clicking `Start Build` button, Screwdriver should create a new event which should inherit all properties from the event from which user clicked `Start Build`. 

- [x] UX should be clear about what happens when user clicks `Start Build` button. User should be aware of the following Execution Flow

Execution Flow.
1. User is viewing pipeline graph for event `T1` at commit SHA `SHA100`. 
1. From the loaded pipeline graph for event `T1` at commit SHA `SHA100` user selects job `X` and clicks on `Start Build` for job `X`. 
1. Screwdriver should create a new event `T2` at commit SHA `SHA100`.  Pipeline for event `T2` should start at job `X` and should have access to all `meta` which  event `T1` had access to.

**Comment by minz1027** [comment]
@jithin1987 Do we want to allow user to just pick any SHA to start from or just the most recent one?

**Comment by jithin1987** [comment]
@minz1027 
1. It will be the SHA of the event user started the build from.
2. If the event was from an external pipeline then it should behave like this feature requirement https://github.com/screwdriver-cd/screwdriver/issues/809

**Comment by minz1027** [comment]
### Update 02/13

## Backend
I think for backend, we already have a function that can achieve most requirements. It can preserve meta from external trigger and previous build:
https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/builds/index.js#L81
Just need to tune it a bit to take in SHA from config and add the logic to /POST event endpoint.

The only case not covered will be `Join`. But we don't even support fully preserve meta for `Join`.https://github.com/screwdriver-cd/screwdriver/issues/883

## UI
After the backend change, when users want to start a build in middle, the UI need to pass in 
- parentBulidId
- pipelineId
- startFrom
- SHA
- CauseMessage(optional)

**Comment by petey** [comment]
UI 
======
* Fixed an issue where all graphs on the page were redrawing every time the event list was updated. This was preventing tooltips from existing longer that the difference in time from the click to the time the refresh occurred (< 5 sec). Instead, it now loops through all the nodes in the graph and updates the status/icon based on the build data. This still happens for each graph on the page every 5 seconds as there is currently no way to indicate whether a redraw is even necessary, but at least the component isn't destroying and recreating the graphs each time.
* Added a popup with a link to the build details for each build bubble that has a build id

TODO:
--------
* [ ] Move the popup closer to the build bubble. The popup doesn't really appear very close to the bubble that was clicked. The x-coordinate seems ok, but the y-coordinate is way off. Not sure why the MouseEvent coordinate is so wrong. These coordinates change even more incorrectly based on if the user is logged in (there is more content on the page).
* [ ] Add an arrow at the top of the popup. It should point at the bubble that was clicked on.
* [ ] Add a link to start an event from that build... This may require information the component does not currently have, but can be passed in. Display additional information about what clicking that link means. Maybe we should have a confirmation modal that pops up.
* [ ] Prevent use of the tooltip and graph clicks when in the "small" mode of the graph.

Misc:
------
Adding this feature into the UI is especially challenging as we are trying to tie functionality into the d3 svg graph that probably shouldn't be done with d3, but requires interaction with the d3 ecosystem (e.g. events and svg markup).

**Comment by minz1027** [comment]
### 02/22

To retrieve the build status from last event, we need to pass in `parentEventId` to the API. So for cases like join, if A failed, B success in first event, when user rerun A, C should still be triggered.
```
A --->
             C
B --->
```

**Comment by tkyi** [comment]
This feature is working in production.
Check out the blog post for more details: http://blog.screwdriver.cd/post/171677387322/rerunning-jobs-and-detached-pipelines
