### ISSUE TITLE
Meta should exist at event level

### ISSUE THREAD

**Issue by jithin1987** [screwdriver-cd/screwdriver#904]
## Context

Today a build's `meta` information is copied over from the parent build (triggering build). This creates a problem when we re-start a failed build or launch an independent job from an existing event. https://github.com/screwdriver-cd/screwdriver/issues/806 Having meta stored at event level, instead of a build level will simplify use case of accessing existing meta from the previous event.

## Objective

1. Store `meta` information at an Event level.
1. With in builds for jobs triggered as part of same event read `meta` from Event instead of copying from parent build.
1. When starting an independent job (https://github.com/screwdriver-cd/screwdriver/issues/806) read initial meta for the new event from the old event from which the job was started.

**Comment by d2lam** [comment]
## **Update 3/7/18**
### After discussing, we have decided:
- Case 1: build does not have a parent build, use the event's metadata.
In this example, restarting the detached job to rollback a deployment will use the event's metadata.
![image uploaded from ios](https://user-images.githubusercontent.com/3401924/37127754-fe37aa92-222b-11e8-8758-1cdad505d13a.jpg)

- Case 2: build has 1 parent build, use the parent build's metadata
In this example, if the user restarts job C, job C will be rerun using job A's metadata.
![image uploaded from ios 3](https://user-images.githubusercontent.com/3401924/37127765-123036a4-222c-11e8-80e2-8e9569b9e71a.jpg)

- Case 3: build has multiple parent builds, use the merged metadata from all the parents
In this example , if the user restarts job F, it will be run using the combined metadata from job A & B. 
![image uploaded from ios 4](https://user-images.githubusercontent.com/3401924/37128422-f727df9e-222e-11e8-9d74-a732ac496242.jpg)


### Reasons why we do this:
If we just use event's metadata for all cases, it will be very hard for users to consume templates. 

For example, in case 2: 
- There are 2 templates: `template_test` that does `meta set image`, and `template_publish` that does `meta get image` inside the code and does something with it. 
- job A and job B both use `template_test`
- job C and job D both use `template_publish`
- If we always use event's metadata, then it's really inconvenient. Users will need to add a poststep for jobA to set `image` to `image_A` and for jobB to set `image` to `image_B`. Then inside jobC and jobD, users will need to set `image_A` to `image` and `image_B` to `image`. 

The idea is to minimize extra overhead on the user's part to consume templates.

Another example, in case 3:
- If user wants to restart job F, they most likely want it to get the previous state of job A & B, not necessarily the whole event's metadata, which will include the metadata set from C,D, and E. 

This behavior is more in line with what we expect based on the pipeline structure and when we try to "rerun" a job.

**Comment by jithin1987** [comment]
Thanks for the detailed summary @d2lam I have a concern for case 3.

**Comment by d2lam** [comment]
**Update 3/8/2018**

- [x]  Meta now exists at event level
- [x]  If no parents and is a restart (has ParentEventId), fetch meta from event

TODO:

- [ ] Change ParentBuildId to an array. For example, in case 3: F will have parentBuildIDs as A's build ID and B's build ID
- [ ] If there are multiple parent builds, launcher should merge their metadata together.

**Comment by tkyi** [comment]
**Update 3/16/2018**
We've merged all PRs to add multiple parent build IDs to `parentBuildId` field and merge parentBuildId metas. The only work left is to verify that the changes are working.

**Comment by tkyi** [comment]
The changes have been verified.
