### ISSUE TITLE
feature: There is no way to announce the downtime.

### ISSUE THREAD

**Issue by yoshwata** [screwdriver-cd/screwdriver#966]
What happened:
It is useful if users are able to know about the downtime from web ui.  We'd like to show the message like `2018/4/2 10:00 - 11:00 : Screwdrivrer will down for maintenance` at top of pages.

What you expected to happen:
Screwdriver UI can show maintenance message.

**Comment by tkyi** [comment]
## Proposal
We should add endpoints to update and delete banner messages in the Screwdriver UI. They should require `admin` permissions (https://github.com/screwdriver-cd/screwdriver/blob/master/config/default.yaml#L31).
1. __PUT__ endpoint to `/banner`
__body__: `{ message: <STRING> }`
2. __DELETE__ endpoint to `/banner`

## Tasks
- [ ] **data-schema**: Add a banner table and schema validation (somewhere here https://github.com/screwdriver-cd/data-schema/tree/master/models)
- [ ] **models**: Add banner model (should be very similar to https://github.com/screwdriver-cd/models/blob/master/lib/collectionFactory.js, https://github.com/screwdriver-cd/models/blob/master/lib/collection.js)
- [ ] **API**: 
  - [ ] Take in auth admin information
  - [ ] Add PUT and DELETE endpoints in a banner folder (see https://github.com/screwdriver-cd/screwdriver/tree/master/plugins) with banner README.md
- [ ] **UI**: Display banner on UI
