### ISSUE TITLE
feature: Support k8s preferred node affinity when creating pods

### ISSUE THREAD

**Issue by tk3fftk** [screwdriver-cd/screwdriver#972]
### Context
As a screwdriver cluster admin, I want to use `nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution` for implementing safety node service-in like below:
- There are two screwdriver clusters (prod, sandbox) in a same k8s cluster.
- The working nodes have `healthy=true` label.
- A target node is service-out status and uncertain of its operation.
  - The node has `need_check=true` label and don't have `healthy=true` label.
- A pod config of the sandbox cluster has`preferredDuringSchedulingIgnoredDuringExecution = "need_check=true"`.
  - Builds work if there is no node with `need_check=true` label.
- A pod config of the prod cluster has `requiredDuringSchedulingIgnoredDuringExecution = "healthy=true"`.
- Remove `need_check` label and add `healthy` label after checking (e.g. run functional test on the target node) in the sandbox cluster.

But we have only `requiredDuringSchedulingIgnoredDuringExecution` currently.

### Objective
Add an ability to configure preferred node affinity like https://github.com/screwdriver-cd/screwdriver/issues/827 with another custom environment variable.

I think the operator of these affinities should be configurable. But the selector config should also be simple so I propose using only `In` operator same as the tolerations.

### Reference
- Related Issue: https://github.com/screwdriver-cd/screwdriver/issues/827
- [Node affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature)

### Tasks
- [x]  Add config to queue-worker
- [x]  Add config to screwdriver
- [x]  Modify executor-k8s to add the config
- [x]  Modify executor-k8s-vm to add the config

**Comment by tk3fftk** [comment]
This might be done and https://github.com/screwdriver-cd/screwdriver/issues/999 is related issue.
